### ISSUE TITLE
Unhandled rejection SequelizeDatabaseError: ER_BLOB_CANT_HAVE_DEFAULT: BLOB/TEXT column 'timezone' can't have a default value

### ISSUE THREAD

**Issue by ruben-farma** [timeoff-management/application#398]
I created a docker image from the Dockerfile in the repo.
with this modification: 
RUN npm install --production 
RUN npm install mysql

```
# -------------------------------------------------------------------
# Minimal dockerfile from alpine base
#
# Instructions:
# =============
# 1. Create an empty directory and copy this file into it.
#
# 2. Create image with: 
#	docker build --tag timeoff:latest .
#
# 3. Run with: 
#	docker run -d -p 3000:3000 --name alpine_timeoff timeoff
#
# 4. Login to running container (to update config (vi config/app.json): 
#	docker exec -ti --user root alpine_timeoff /bin/sh
# --------------------------------------------------------------------
FROM alpine:3.8

EXPOSE 3000

LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.docker.cmd="docker run -d -p 3000:3000 --name alpine_timeoff"

RUN apk add --no-cache \
    git \
    make \
    nodejs npm \
    python \
    vim
    
RUN adduser --system app --home /app
USER app
WORKDIR /app
RUN git clone https://github.com/timeoff-management/application.git timeoff-management
WORKDIR /app/timeoff-management

RUN npm install --production 
RUN npm install mysql

CMD npm start
```

Then I run it with docker-compose and the config files in readonly option as volume:
```
app:
    image: timeoff
    container_name: 'timeoff_app'
    #    links:
    #      - db:db
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./volumes/config:/app/timeoff-management/config
#      - ./volumes/config:/app/timeoff-management/config:ro
    ports:
      - '3000:3000'
    depends_on:
      - "db"
  db:
    image: 'mariadb:10.1.22'
    container_name: 'timeoff_db'
    restart: unless-stopped
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/backups:/var/backups
    environment:
      - MYSQL_ROOT_PASSWORD=timeoff
      - MYSQL_DATABASE=timeoff
      - MYSQL_USER=timeoff
      - MYSQL_PASSWORD=timeoff
```
#-db.json

```
  "production": {
    "username": "timeoff",
    "password": "timeoff",
    "database": "timeoff",
    "host": "timeoff_db",
    "dialect": "mysql"
  }
```

 [Node: 8.14.0, CLI: 2.5.1, ORM: 3.35.1, mysql: ^2.17.1]

docker logs timeoff_app
```

> TimeOff.Management@0.10.0 start /app/timeoff-management
> node bin/wwww

Unhandled rejection SequelizeDatabaseError: ER_BLOB_CANT_HAVE_DEFAULT: BLOB/TEXT column 'timezone' can't have a default value
    at Query.formatError (/app/timeoff-management/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query.<anonymous> (/app/timeoff-management/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/app/timeoff-management/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/app/timeoff-management/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/app/timeoff-management/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/timeoff-management/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/timeoff-management/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/app/timeoff-management/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/app/timeoff-management/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

```
